name: Publish (09:00 TPE) — Build → push gh-pages

on:
  workflow_dispatch: {}
  schedule: [ { cron: "0 * * * *" } ]   # 每小時喚醒；只在 09 點真正執行
  push: { branches: [ main ] }

permissions:
  contents: write    # 需要寫入 gh-pages 分支

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Gate to 09:00 TPE
        run: export TZ=Asia/Taipei; [ "$(date +%H)" = "09" ] || { echo "skip"; exit 0; }

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11", cache: "pip" }

      - run: pip install -r backend/requirements.txt

      - name: Build site to ./out
        env: { LOCAL_OUT: out }
        run: python -m scripts.daily

      # 分支式 Pages：把 out/ 發佈到 gh-pages 分支根目錄
      - name: Deploy to gh-pages (branch-based Pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: gh-pages
          force_orphan: true    # 清爽歷史；首次沒有分支也會自動建立
          commit_message: "publish: ${{ github.sha }}"
