name: Publish (TPE 09:00) - Build and push gh-pages

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force run (ignore 09:00 TPE gate)'
        required: false
        default: 'false'
  schedule:
    - cron: '0 * * * *'   # hourly wake
  push:
    branches:
      - main

permissions:
  contents: write   # need to push gh-pages

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Gate to 09:00 TPE (or force)
        run: |
          export TZ=Asia/Taipei
          H=$(date +%H)
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.force }}" = "true" ]; then
            echo "Force run -> continue"
          elif [ "$H" = "09" ]; then
            echo "09:00 TPE -> continue"
          else
            echo "Skip: not 09:00 TPE and no force=true"
            exit 0
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: pip install -r backend/requirements.txt

      - name: Build site to ./out
        env:
          LOCAL_OUT: out
        run: python -m scripts.daily

      - name: Deploy to gh-pages (branch-based Pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "publish: ${{ github.sha }}"
