name: Suggest (TPE 08:30) — 10 topics

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force run (ignore 08:00 TPE gate)'
        required: false
        default: 'false'
  schedule:
    - cron: '0 * * * *'   # hourly wake

permissions:
  contents: write
  issues: write

jobs:
  suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Decide run gate (TPE 08 or force)
        run: |
          export TZ=Asia/Taipei
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.force }}" = "true" ]; then
            echo "RUN=true" >> $GITHUB_ENV
          elif [ "$(date +%H)" = "08" ]; then
            echo "RUN=true" >> $GITHUB_ENV
          else
            echo "RUN=false" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v4
        if: env.RUN == 'true'

      - name: Generate 10 topics (fallback) & open/update issue
        if: env.RUN == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
            const title = `[Suggest] ${today} 今日 10 題`;
            const items = Array.from({length:10},(_,i)=>({no:i+1,title:`今日研究題目 ${i+1}`,tags:["research"]}));
            const body = "請留言 `/pick 2,7` 或 `/pick 2 7`\n\n```json\n"+JSON.stringify({date:today,items},null,2)+"\n```";
            const { data: issues } = await github.rest.issues.listForRepo({ owner: context.repo.owner, repo: context.repo.repo, state:'open', per_page:100 });
            const found = issues.find(x=>x.title===title);
            if (found) {
              await github.rest.issues.update({ owner: context.repo.owner, repo: context.repo.repo, issue_number: found.number, body, labels:['daily-suggest'] });
            } else {
              await github.rest.issues.create({ owner: context.repo.owner, repo: context.repo.repo, title, body, labels:['daily-suggest'] });
            }
