name: Suggest (08:30 TPE) — 10 topics
on:
  workflow_dispatch: {}
  schedule: [ { cron: "0 * * * *" } ]
permissions:
  contents: write
  issues: write
jobs:
  suggest:
    runs-on: ubuntu-latest
    steps:
      - name: Gate to 08:00 TPE
        run: export TZ=Asia/Taipei; [ "$(date +%H)" = "08" ] || { echo "skip"; exit 0; }
      - name: Generate 10 topics (fallback)
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
            const items = Array.from({length:10},(_,i)=>({no:i+1,title:`今日研究題目 ${i+1}`,tags:["research"]}));
            const body = "請留言 `/pick 2,7` 或 `/pick 2 7`\n\n```json\n"+JSON.stringify({date:today,items},null,2)+"\n```";
            const title = `[Suggest] ${today} 今日 10 題`;
            try {
              const { data: issues } = await github.rest.issues.listForRepo({ owner: context.repo.owner, repo: context.repo.repo, labels: "daily-suggest", state: "open", per_page: 100 });
              const found = issues.find(x=>x.title===title);
              if (found) await github.rest.issues.update({ owner: context.repo.owner, repo: context.repo.repo, issue_number: found.number, body });
              else await github.rest.issues.create({ owner: context.repo.owner, repo: context.repo.repo, title, body, labels: ["daily-suggest"] });
            } catch (e) { core.setFailed(e.message); }
